in mandatory2.maude .

*** Excercise 79
red last(nil) .
red last(200 2) .
red last(1 2 3 4 5) .
red last(5 7 6) .

red rest(nil) .
red rest(200 2) .
red rest(1 2 3 4 5) .
red rest(5 7 6) .

*** Excercise 80
red first(nil) .
red first(200 2) .
red first(1 2 3 4 5) .
red first(5 7 6) .

red reverse(nil) .
red reverse(200 2) .
red reverse(1 2 3 4 5) .
red reverse(5 7 6) .

red max(nil) .
red reverse(200 2) .
red reverse(1 2 3 4 5) .
red reverse(5 7 6) .

red isSorted(nil) .
red isSorted(200 2) .
red isSorted(1 2 3 4 5) .
red isSorted(5 7 6) .
