in mandatory2-part1.maude .

*** Excercise 79
red last(nil) .
red last(200 2) .
red last(1 2 3 4 5) .
red last(5 7 6) .

red rest(nil) .
red rest(200 2) .
red rest(1 2 3 4 5) .
red rest(5 7 6) .

*** Excercise 80
red first(nil) .
red first(200 2) .
red first(1 2 3 4 5) .
red first(5 7 6) .

red reverse(nil) .
red reverse(200 2) .
red reverse(1 2 3 4 5) .
red reverse(5 7 6) .

red max(nil) .
red reverse(200 2) .
red reverse(1 2 3 4 5) .
red reverse(5 7 6) .

red isSorted(nil) .
red isSorted(200 2) .
red isSorted(1 2 3 4 5) .
red isSorted(5 7 6) .

*** Excercise 82
red (1 2 3 4) >lex (1 2 3) .
red (2 3 4) >lex (1 2 3 4) .
red (1) >lex (1 0) .
red (1 2 3) >lex (1 2 3) .
red (2 5 6) >lex (2 4 678 12) .

in mandatory2-part2.maude .

*** Excercise 85
red mult(0, none) .
red mult(2, 1 2 2 3 4 5 6 7 1 2) .

*** red max(nil) .Nil is undefined for Int .
red max(2) .
red max(1 2 3 5 6 7 3 5 6 8) .

red empty?(none) .
red empty?(0) .
red empty?(1 3 4 5 6) .

red none >mul none .
red none >mul (1 2 3 4) .
red (1 2 3 4) >mul none .
red (1 2 3 4) >mul (1 2 3 4) .
red (2 3 5) >mul (3 5 2) .
